# VERSION 3.3
# AUTHOR:         Nicolas Lamirault <nicolas.lamirault@gmail.com>
# DESCRIPTION:    portefaix/base

FROM alpine:3.3
MAINTAINER Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Install base packages
RUN apk add --update bash && rm -rf /var/cache/apk/*

CMD ["/bin/bash"]
